[mongodb]
mongodb.vandevops.online

[catalogue]
catalogue.vandevops.online

[user]
user.vandevops.online

[cart]
cart.vandevops.online

[web]
web.vandevops.online

[redis]
redis.vandevops.online

[mysql]
mysql.vandevops.online

[shipping]
shipping.vandevops.online

[rabbitmq]
rabbitmq.vandevops.online

[payment]
payment.vandevops.online

[dispatch]
dispatch.vandevops.online


; [all:vars]
; ansible_password=DevOps321