- name: "install {{component}}"
  hosts: "{{component}}"
  vars_files:
  - variables.yaml
  become: yes
  roles:
  - "{{component}}"

  # ansible-playbook -i inventory.ini -e ansible_user=centos -e ansible_password=DevOps321 main.yaml -e component=mongodb.yaml
