# Day 27

- name: "configure {{ component }} server"
  hosts: "{{ component }}"
  become: yes
  roles:
    - "{{ component }}"

# eg:
# ansible-playbook -e component=mongodb roboshop.yaml ->
# {{ component }} value is taken from inventory.ini file based on the command line arg,
# and also it executes tasks from roles-mongodb-tasks-main.yaml file,
# and also takes related files from roles-mongodb-files-mongo.repo file,
# also take username, password and other related {{ HOST }} names from directory named group_vars and file name all.yaml file.


# eg:
# ansible-playbook -e component=catalogue roboshop.yaml ->
# {{ component }} value is taken from inventory.ini file based on the command line arg,
# and also it executes tasks from roles-catalogue-meta-main.yaml file and check for dependencies, and hence
# now it goes to common-tasks-main.yaml file and executes it,
# now it goes to roles-catalogue-tasks-main.yaml file and checks for import_role and executes common-tasks-app-setup.yaml as given,
# also take username, password and other related {{ HOST }} names from directory named group_vars and file name all.yaml file.

# to run all logs in background using nohup and & and save in var/log/ansible.log file
# nohup ansible-playbook -e component=catalogue roboshop.yaml  &>/var/log/ansible.log &

# handlers - they are notifiers , i.e.you can call task-b when task-a changes, eg: when configuration chnges, you can restart the application.